/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface DetectionDetectResponse {
    /** A status code denoting success or failure. */
    status?: string;
    /** The detections response includes 3 elements: the bbox array, a confidence value, and a class. The bbox array is an array of numbers describing the bounding box coordinates for your objects listed in order as [x1, y1, x2, y2]. The confidence score is a value between 0 and 1 rating how confident the object detection output is based on your model and the image provided. The class is the class name of the detected object. */
    detections?: unknown[];
}
