/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as errors from "../../errors/index";
import * as AmniscientApi from "../index";

export class UnauthorizedError extends errors.AmniscientApiError {
    constructor(body: AmniscientApi.UnauthorizedErrorBody) {
        super({
            message: "UnauthorizedError",
            statusCode: 401,
            body: body,
        });
        Object.setPrototypeOf(this, UnauthorizedError.prototype);
    }
}
