/**
 * This file was auto-generated by Fern from our API Definition.
 */

export class AmniscientApiTimeoutError extends Error {
    constructor(message: string) {
        super(message);
        Object.setPrototypeOf(this, AmniscientApiTimeoutError.prototype);
    }
}
