/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface DetectionDetectRequest {
    /** Your organization identifier */
    organizationId: string;
    file?: unknown;
}
