/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as AmniscientApi from "../../../../api/index";
import * as core from "../../../../core";

export const DetectionDetectResponse: core.serialization.ObjectSchema<
    serializers.DetectionDetectResponse.Raw,
    AmniscientApi.DetectionDetectResponse
> = core.serialization.object({
    status: core.serialization.string().optional(),
    detections: core.serialization.list(core.serialization.unknown()).optional(),
});

export declare namespace DetectionDetectResponse {
    export interface Raw {
        status?: string | null;
        detections?: unknown[] | null;
    }
}
