/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../index";
import * as AmniscientApi from "../../../api/index";
import * as core from "../../../core";

export const LoadModelRequest: core.serialization.Schema<
    serializers.LoadModelRequest.Raw,
    AmniscientApi.LoadModelRequest
> = core.serialization.object({
    organizationId: core.serialization.property("organization_id", core.serialization.string()),
});

export declare namespace LoadModelRequest {
    export interface Raw {
        organization_id: string;
    }
}
