/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface BadRequestErrorBody {
    /** A status code denoting success or failure. */
    status?: string;
    /** A message describing your error. */
    message?: string;
}
