/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface LoadModelResponse {
    /** A status code denoting success or failure. */
    status?: string;
    message?: string;
    /** The model ID of the model you loaded. This should match the model ID that was input as a path parameter to this API. */
    modelId?: string;
}
