/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as AmniscientApi from "../../../../api/index";
import * as core from "../../../../core";

export const ModelLoadModelResponse: core.serialization.ObjectSchema<
    serializers.ModelLoadModelResponse.Raw,
    AmniscientApi.ModelLoadModelResponse
> = core.serialization.object({
    status: core.serialization.string().optional(),
    message: core.serialization.string().optional(),
    modelId: core.serialization.property("model_id", core.serialization.string().optional()),
});

export declare namespace ModelLoadModelResponse {
    export interface Raw {
        status?: string | null;
        message?: string | null;
        model_id?: string | null;
    }
}
