/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * @example
 *     {
 *         organizationId: "organization_id"
 *     }
 */
export interface DetectRequest {
    /** Your organization identifier */
    organizationId: string;
}
