/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as environments from "../../../../environments";
import * as core from "../../../../core";
import * as AmniscientApi from "../../../index";
import * as serializers from "../../../../serialization/index";
import urlJoin from "url-join";
import * as errors from "../../../../errors/index";

export declare namespace Model {
    export interface Options {
        environment?: core.Supplier<environments.AmniscientApiEnvironment | string>;
        /** Specify a custom URL to connect the client to. */
        baseUrl?: core.Supplier<string>;
        /** Override the x-api-key header */
        apiKey: core.Supplier<string>;
    }

    export interface RequestOptions {
        /** The maximum time to wait for a response in seconds. */
        timeoutInSeconds?: number;
        /** The number of times to retry the request. Defaults to 2. */
        maxRetries?: number;
        /** A hook to abort the request. */
        abortSignal?: AbortSignal;
        /** Override the x-api-key header */
        apiKey?: string;
        /** Additional headers to include in the request. */
        headers?: Record<string, string>;
    }
}

export class Model {
    constructor(protected readonly _options: Model.Options) {}

    /**
     * Initializes a model for inference. This endpoint must be called before running any detections.
     *
     * @param {string} modelId - The model ID of an active and trained AI model within your organization
     * @param {AmniscientApi.ModelLoadModelRequest} request
     * @param {Model.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link AmniscientApi.BadRequestError}
     * @throws {@link AmniscientApi.UnauthorizedError}
     *
     * @example
     *     await client.model.loadModel("model_id", {
     *         organizationId: "organization_id"
     *     })
     */
    public async loadModel(
        modelId: string,
        request: AmniscientApi.ModelLoadModelRequest,
        requestOptions?: Model.RequestOptions,
    ): Promise<AmniscientApi.ModelLoadModelResponse> {
        const _response = await core.fetcher({
            url: urlJoin(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.AmniscientApiEnvironment.Default,
                `loadModel/${encodeURIComponent(modelId)}`,
            ),
            method: "POST",
            headers: {
                "x-api-key": await core.Supplier.get(this._options.apiKey),
                "X-Fern-Language": "JavaScript",
                "X-Fern-SDK-Name": "",
                "X-Fern-SDK-Version": "1.0.0",
                "X-Fern-Runtime": core.RUNTIME.type,
                "X-Fern-Runtime-Version": core.RUNTIME.version,
                ...requestOptions?.headers,
            },
            contentType: "application/json",
            requestType: "json",
            body: serializers.ModelLoadModelRequest.jsonOrThrow(request, { unrecognizedObjectKeys: "strip" }),
            timeoutMs: requestOptions?.timeoutInSeconds != null ? requestOptions.timeoutInSeconds * 1000 : 60000,
            maxRetries: requestOptions?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
        });
        if (_response.ok) {
            return serializers.ModelLoadModelResponse.parseOrThrow(_response.body, {
                unrecognizedObjectKeys: "passthrough",
                allowUnrecognizedUnionMembers: true,
                allowUnrecognizedEnumValues: true,
                breadcrumbsPrefix: ["response"],
            });
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new AmniscientApi.BadRequestError(_response.error.body);
                case 401:
                    throw new AmniscientApi.UnauthorizedError(
                        serializers.UnauthorizedErrorBody.parseOrThrow(_response.error.body, {
                            unrecognizedObjectKeys: "passthrough",
                            allowUnrecognizedUnionMembers: true,
                            allowUnrecognizedEnumValues: true,
                            breadcrumbsPrefix: ["response"],
                        }),
                    );
                default:
                    throw new errors.AmniscientApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                    });
            }
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.AmniscientApiError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                });
            case "timeout":
                throw new errors.AmniscientApiTimeoutError("Timeout exceeded when calling POST /loadModel/{model_id}.");
            case "unknown":
                throw new errors.AmniscientApiError({
                    message: _response.error.errorMessage,
                });
        }
    }
}
