/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as AmniscientApi from "../../api/index";
import * as core from "../../core";

export const LoadModelResponse: core.serialization.ObjectSchema<
    serializers.LoadModelResponse.Raw,
    AmniscientApi.LoadModelResponse
> = core.serialization.object({
    status: core.serialization.string().optional(),
    message: core.serialization.string().optional(),
    modelId: core.serialization.property("model_id", core.serialization.string().optional()),
});

export declare namespace LoadModelResponse {
    export interface Raw {
        status?: string | null;
        message?: string | null;
        model_id?: string | null;
    }
}
