/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as AmniscientApi from "../../api/index";
import * as core from "../../core";

export const UnauthorizedErrorBody: core.serialization.ObjectSchema<
    serializers.UnauthorizedErrorBody.Raw,
    AmniscientApi.UnauthorizedErrorBody
> = core.serialization.object({
    status: core.serialization.string().optional(),
    message: core.serialization.string().optional(),
});

export declare namespace UnauthorizedErrorBody {
    export interface Raw {
        status?: string | null;
        message?: string | null;
    }
}
