/**
 * This file was auto-generated by Fern from our API Definition.
 */

export const AmniscientApiEnvironment = {
    Default: "https://tytbrazyv9.execute-api.us-east-1.amazonaws.com/prod/inference",
} as const;

export type AmniscientApiEnvironment = typeof AmniscientApiEnvironment.Default;
